### ISSUE TITLE
disabled NumericTextBox

### ISSUE THREAD

**Issue by adismhd** [pablopioli/BlazorNumericTextbox#6]
is it possible to disabled NumericTextBox?

i try this and not work
`<NumericTextBox TItem="decimal" disabled Format="###,##0.00"></NumericTextBox>`

then i try this
`<NumericTextBox TItem="decimal" readonly Format="###,##0.00"></NumericTextBox>`
but the value can still be changed

**Comment by pablopioli** [comment]
As the control is fully rendered in a custom way there isn't a disabled state programmed yet.
I usually just render conditionally a simple text for the disabled state.
